### ISSUE TITLE
Safe-guard distributed configuration files

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-server#1]
How can we ensure that configuration files which should be maintained 100% by the package is not changed by users?

* Add in README files to folders
* Move `/etc/kolibri/` stuff to `/etc/kolibri/server/dist/` and put a README in each directory
* Write comments at the top of each file that should not be changed

Ensure that README files contain pointers to where users SHOULD add their changes.

Related: https://github.com/learningequality/kolibri-installer-debian/issues/56

**Comment by jredrejo** [comment]
We shouldn't ensure that. 
Users are the owner of their servers, they must be able to change anything.
As you say, I think our responsability is limited to leave a README file there stating that the package could not work if they change it.
I don't see  how moving the package files to server/dist is going to provide any benefit here.

**Comment by benjaoming** [comment]
Please see the PR @jredrejo as it indicates more precisely what the intention is.
