### ISSUE TITLE
I don't want to update my kolibri.service

### ISSUE THREAD

**Issue by KotwGrone96** [learningequality/kolibri-server#100]
Hi, I would like to use this package "kolibri-server" without upgrade to 0.16 version.
Is that possible? I currently have 0.15.12 version.

**Comment by rtibbles** [comment]
No - the newer version of kolibri-server has changes specific to the 0.16 version of kolibri, so would not work with older versions of kolibri.

**Comment by KotwGrone96** [comment]
Thanks for your message, If I would like to use use Nginx with 0.15.12 version, Is there any config?
How can I activate Kolibri in production mode, because I understand that I'm in developer mode.
In the information of the app I can read "Server: Cheroot/unknown"

**Comment by jredrejo** [comment]
@KotwGrone96 :

- on one hand, `Server: Cheroot/unknown` means you're using the web server kolibri provides, it can be used safely in production mode. Depending on your hardware it might not squeeze all the hardware power but it's good enough for most cases.
- on the other hand, if you don't want to upgrade kolibri, you still can use [kolibri-server ](url)version 0.4, still available at https://launchpad.net/~learningequality/+archive/ubuntu/kolibri/+packages to be downloaded manually

Finally, all configs used by `kolibri-server` with nginx, uwsgi and redis are visible at its repository: https://github.com/learningequality/kolibri-server you can take a look there to create your own nginx config if you prefer that option.

Hope this helps
