### ISSUE TITLE
Errors while importing channels on `kolibri-server`

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri-server#13]
### Observed behavior

Unable to import content from Studio:

During the first attempt to import after installation, it seemed that user got disconnected, even though the service was still active:

![ubuntu 16 04 3 start running - oracle vm virtualbox_438](https://user-images.githubusercontent.com/1457929/53535884-93609880-3b04-11e9-9a1e-d9b63efad345.png)

After restarting the system, different error while importing channels:
![import-kolibri-server](https://user-images.githubusercontent.com/1457929/53535894-9a87a680-3b04-11e9-94f9-0a058c304d7e.gif)

### Expected behavior

Able to import content channels without errors.

### User-facing consequences

…

### Errors and logs

[kolibri.log](https://github.com/learningequality/kolibri/files/2913073/kolibri.log)

### Steps to reproduce

…

### Context

Version:           0.12.0b10
OS:                Linux-4.4.0-142-generic-x86_64-with-Ubuntu-16.04-xenial
Installer:         kolibri(apt) with kolibri-server Version: 0.2-0beta3
Server:            nginx/1.10.3 (Ubuntu)
Browser:         Firefox & Chrome

cc @jredrejo

**Comment by indirectlylit** [comment]
@jredrejo transferred issue to `kolibri-server` repo

**Comment by jredrejo** [comment]
@mrpau-julius I am not able to reproduce the problem, running kolibri-server in one vm and accesing from my browser. 
How are you trying it? having both the server and the browser in the same machine? does it happen everytime you try to import or only sometimes? if it happens sometimes, any hint to help me reproduce it?

**Comment by mrpau-julius** [comment]
@jredrejo, In the latest version of Kolibri-server 0.12.2. I can't reproduce it. I tried it several times installing the Kolibri-server, there no track or issues exist.

**Comment by jredrejo** [comment]
that's great @mrpau-julius I am closing this issue then. Feel free to reopen it if you see it again and can find a way to reproduce it.
Thanks very much
