### ISSUE TITLE
Content import progress value is more than 100% on 'Kolibri-server'

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri-server#14]
### Observed behavior

While I import an `African Storybook` channel using the local drive, I observe the progress value are more than 100 percent and I get an error on console.
 

![Screenshot from 2019-03-13 15-19-21](https://user-images.githubusercontent.com/38421180/54261043-ab74f500-45a5-11e9-9280-2531d3a7a733.png)

### Expected behavior

The progress bar must be exactly 100 percent.

### Errors and logs

[kolibri.log](https://github.com/learningequality/kolibri/files/2960287/kolibri.log)
[server.log](https://github.com/learningequality/kolibri/files/2960289/server.log)

### Context

Version: 0.12.1
OS: Linux-4.15.0-29-generic-x86_64-with-Ubuntu-16.04-xenial
Installer: kolibri(apt) with kolibri-server Version: 0.2.1-0buntu1
Server: nginx/1.10.3 (Ubuntu)
Browser: Firefox

cc @jredrejo

**Comment by lyw07** [comment]
Did some more investigations and here are the steps to reproduce the error:
1. Install kolibri-server
2. import 10GB content from a KA channel, cancel the import at the progress 1% (one error here is that the channel was not be marked as available, although it is supposed to be)
3. import some more content. If we import a new channel, channel database file download will fail.

the error will be not show up if we refresh the page after step 2
I think this issue has the same underlying cause of the issue https://github.com/learningequality/kolibri-server/issues/13

**Comment by indirectlylit** [comment]
cc @jredrejo  --^

**Comment by benjaoming** [comment]
Seems related to Iceqube and several workers? @jredrejo would it make sense to request to see if this can be reproduced with the UWSGI configuration edited to have on a single worker?

**Comment by jredrejo** [comment]
@benjaoming no need, I can confirm it's an iceqube problem. There's a new version of iceqube on the way, with important changes in the way these tasks are handled. I am waiting for it to be approved to test it.

**Comment by jredrejo** [comment]
@mrpau-julius I have tested this using 
```
kolibri                                    0.12.8-0ubuntu1          
kolibri-server                             0.3.2-0ubuntu1          
```
and the issue does not happen anymore.
Please, can you check it too and close this issue if that's the case?

**Comment by mrpau-julius** [comment]
Yes, you're right @jredrejo, this issue has been fixed in the latest version of Kolibri server. I am closing this now.
