### ISSUE TITLE
Error during nginx reload during installation

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri-server#16]
I already had nginx-core installed on my Ubuntu 18.04 LTS server. Upon installation of kolibri-server 0.2.5, the nginx service could not reload due to this error -

```
Jul 05 11:22:00 server systemd[1]: Reloading A high performance web server and a reverse proxy server.
Jul 05 11:22:01 server nginx[13078]: nginx: [emerg] open() "/home/mssadmin/.kolibri/nginx.conf" failed (2: No such file or directory) in /etc/kolibri/nginx.d/099-user.conf:1
Jul 05 11:22:01 server systemd[1]: nginx.service: Control process exited, code=exited status=1
Jul 05 11:22:01 server systemd[1]: Reload failed for A high performance web server and a reverse proxy server.
```

However, it did succeed on subsequent attempts. Seems the installer tried to reload the nginx server prior to creation of the file / link - ```/home/mssadmin/.kolibri/nginx.conf```.

**Comment by intelliant01** [comment]
Problem persists in kolibri-server 0.3.0.

**Comment by benjaoming** [comment]
@jredrejo do we need to somehow force the creation of `~/.kolibri` during `postinst configure`? Could it be done very naively by invoking `kolibri status`?

Am thinking about this sequence: https://github.com/learningequality/kolibri-server/blob/master/debian/postinst#L22

**Comment by jredrejo** [comment]
@benjaoming actually https://github.com/learningequality/kolibri-server/blob/master/debian/postinst#L21 should create the needed nginx conf. 
@intelliant01 I am not able to reproduce this, you say you see it in 0.3.0 too, could you help me with the needed steps to reproduce the problem?

**Comment by intelliant01** [comment]
@jredrejo This can be reproduced every time with these steps -

1. Uninstall kolibri-server and kolibri completely.
2. Remove nginx.conf that has been created inside .kolibri folder during the previous installation.
3. Install kolibri-server and keep an eye on the installation output.

**Comment by benjaoming** [comment]
@jredrejo I think this might be because `/etc/kolibri/nginx.d/099-user.conf` exists from the previous installation. We need to disable it in `postrm` such that a broken nginx config isn't left enabled on the system?

**Comment by intelliant01** [comment]
Yes, I forgot to mention that the uninstall is not doing a complete cleanup. 
Tried both ```apt remove``` and ```apt pruge```.  Shall create a separate issue for this.

**Comment by intelliant01** [comment]
@jredrejo @benjaoming To sum it up, the error reported is because nginx reload is being attempted before nginx.conf is created but a reference to the same already exists at ` /etc/kolibri/nginx.d/099-user.conf`. One may not be able to reproduce this error if after uninstalling kolibri-server we do not manually cleanup the nginx.conf.
Have created #29 to address the issue with uninstalling.

**Comment by benjaoming** [comment]
Just made a clean installation on a clean Raspbian Stretch. I had installed nginx before installing kolibri.

The final bits of `sudo apt install kolibri kolibri-server` looked like this:

```
WARNING  Options file /home/pi/.kolibri/options.ini has been updated; server restart is required before change will take effect.
WARNING  Options file /home/pi/.kolibri/options.ini has been updated; server restart is required before change will take effect.
WARNING  Options file /home/pi/.kolibri/options.ini has been updated; server restart is required before change will take effect.
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
Created symlink /etc/systemd/system/multi-user.target.wants/kolibri-server.service → /lib/systemd/system/kolibri-server.service.
Processing triggers for systemd (232-25+deb9u11) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
```

 and got this from `systemctl status nginx.service`:

```
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: active (running) (Result: exit-code) since Thu 2019-08-22 17:47:13 BST; 40min ago
     Docs: man:nginx(8)
 Main PID: 1609 (nginx)
   CGroup: /system.slice/nginx.service
           ├─1609 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
           ├─3567 nginx: worker process
           ├─3568 nginx: worker process
           ├─3569 nginx: worker process
           ├─3570 nginx: worker process
           └─3571 nginx: cache manager process

Aug 22 17:47:13 raspberrypi systemd[1]: Starting A high performance web server and a reverse proxy server...
Aug 22 17:47:13 raspberrypi systemd[1]: Started A high performance web server and a reverse proxy server.
Aug 22 18:23:38 raspberrypi systemd[1]: Reloading A high performance web server and a reverse proxy server.
Aug 22 18:23:38 raspberrypi nginx[3396]: nginx: [emerg] open() "/home/pi/.kolibri/nginx.conf" failed (2: No such file or directory) in /etc/kolibri/ngi
Aug 22 18:23:38 raspberrypi systemd[1]: nginx.service: Control process exited, code=exited status=1
Aug 22 18:23:38 raspberrypi systemd[1]: Reload failed for A high performance web server and a reverse proxy server.
Aug 22 18:24:00 raspberrypi systemd[1]: Reloading A high performance web server and a reverse proxy server.
Aug 22 18:24:00 raspberrypi systemd[1]: Reloaded A high performance web server and a reverse proxy server.
Aug 22 18:24:16 raspberrypi systemd[1]: Reloading A high performance web server and a reverse proxy server.
Aug 22 18:24:16 raspberrypi systemd[1]: Reloaded A high performance web server and a reverse proxy server.
```

**Comment by benjaoming** [comment]
Reopening this, because @intelliant01 also reported something similar.

@intelliant01 could you confirm if you can reproduce the above or if you have a different issue?

**Comment by jredrejo** [comment]
@benjaoming the problem you comment is related to the installation while the problem @intelliant01 commented and that was solved was related to uninstallation and purge of the package.
 Please create a new issue for your problem to avoid mixing topics.

**Comment by intelliant01** [comment]
@jredrejo I had infact reported this issue as an error on installation. The ”uninstallation and purge” discussion happened as a consequence of trying to reproduce the original problem during installation. I think this issue must be reopened.
