### ISSUE TITLE
improve nginx HTML-based error messages

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-server#17]
We've gotten feedback that 

> When it shows Kolibri busy, the teachers will get confused as they won't know what needs to be done. This will intern impact classrooms.

(https://github.com/learningequality/kolibri/issues/5753)

Let's improve the messages to...

* make them less scary-looking, using standard Noto fonts and nice formatting
* improve the explanations of what's happening
* auto-refresh every few seconds

**Comment by benjaoming** [comment]
@indirectlylit note that adding complexity to error pages is perhaps not the best idea as it can result in more errors - also, for static assets, this would put a dependency on the structure of kolibri's static assets in this debian package.

Would making text-only changes and auto-refresh be a good first step? Note that auto-refresh can be achieved without JS: https://en.wikipedia.org/wiki/Meta_refresh

**Comment by benjaoming** [comment]
Also, great idea with the auto-refresh!

**Comment by indirectlylit** [comment]
> for static assets, this would put a dependency on the structure of kolibri's static assets in this debian package

agreed, these should be stand-alone HTML files baked into the `kolibri-server` package, with no dependency on `kolibri`
