### ISSUE TITLE
kolibri-server service requires manual restart to access kolibri

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri-server#18]
kolibri and kolibri-server service start upon system boot up. Post vacuuming as observed via kolibri.txt log, the browser still shows ```502 Bad Gateway``` error. Once the vacuuming and ping test are done with as seen in the log, kolibri-server needs to be restarted to move ahead of the 502 response and access Kolibri.

A thought - the db size is 2.6 GB, hence it may be taking much longer than the anticipated sleep/wait for kolibri-server to start after kolibri.

**Environment**
Hardware: Celeron Dual Core + 4 GB RAM + 7200 RPM SATA HDD
kolibri deb version 0.12.7 
kolibri-server 0.12.5
Ubuntu 18.04
sqlite database size of Kolibri is 2.6 GB.

**Comment by intelliant01** [comment]
Figured out why this was happening.

I had updated kolibri deb to 0.12.7 individually as kolibri-server is still at 0.12.5 which enabled the kolibri service as well. Have now disabled the kolibri service, preventing it to start upon boot, and all is working is expected as kolibri-server service is alone *in-charge* now.

Noteworthy that even with 2.6 GB db the startup time is under 4 minutes.

**Comment by benjaoming** [comment]
@intelliant01 are you in touch with anyone about this DB footprint? I think it's interesting to know the reasoning for such a large DB and how it can be reduced or split up.

**Comment by intelliant01** [comment]
@benjaoming Yes, the large db size has been brought up in discussions with Richard and Rafael over email.
Have even been discussing in a [community thread](https://community.learningequality.org/t/implications-of-large-db-sqlite3-file-for-kolibri-performance/1218?u=shrenik)

The reasoning behind the size seems fine as it is of a production system with over 200 users and more than a year of usage data.

**Comment by benjaoming** [comment]
Thanks so much for the references, @intelliant01 - will ponder this and respond in the forums if I can come up with something.
