### ISSUE TITLE
redis does not start

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri-server#21]
redis does not start upon installation of kolibri-server though it is specified for caching in options.ini. Even after manually starting redis and restarting kolibri-server, no kolibri screen can be loaded.

This is the what is available via browser console -
![licecap_0NWZOeODDJ](https://user-images.githubusercontent.com/2577060/62145260-bb9d2f00-b310-11e9-8629-0206d9284e7c.png)

Seems some old files are being served via cache. I had earlier upgraded from 0.12.6a2 to 0.12.7.

kolibri-server 0.3.0
kolibri 0.12.7
Ubuntu 18.04

**Comment by jredrejo** [comment]
hello @intelliant01  how did you install redis? did you do any manual config on it? the default redis-server installation sets it up to start on boot.

**Comment by intelliant01** [comment]
@jredrejo default installation while installing kolibri-server 0.3.0.
Had experienced it over two attempts of installtion. It is enabled but not started.

**Comment by jredrejo** [comment]
> @jredrejo default installation while installing kolibri-server 0.3.0.
> Had experienced it over two attempts of installtion. It is enabled but not started.

but you had to do something when installing `redis-server` for it not to start. Automatic installation sets it to start by default.

**Comment by intelliant01** [comment]
@jredrejo did a clean install on a newly installed OS. It works as expected and ```redis-server``` starts automatically. 
Can't yet put my finger on what is causing it not to start automatically immediately upon installation on the above referenced system. Now I shall shift my focus on solving this puzzle.

Can you suggest what could be causing this?
> Seems some old files are being served via cache. I had earlier upgraded from 0.12.6a2 to 0.12.7.

**Comment by indirectlylit** [comment]
@intelliant01 FYI @jredrejo is on vacation. I expect your recent `kolibri-server` issues will get more attention when he returns. Thanks for your testing and patience!

**Comment by intelliant01** [comment]
@indirectlylit Thanks for the information.

**Comment by jredrejo** [comment]
@intelliant01 hello again,
it seems your redis installation has some kind of problem in one of the servers and it's not able to start.
There are two commands that could help to find out the reason. After doing
`service redis restart`
can you paste the output of
`service redis status`
and of
`tail /var/log/redis/redis-server.log`

**Comment by intelliant01** [comment]
@jredrejo i could not reproduce this problem after a clean reinstall on the "problem" server. Hence had closed this. We can move ahead of this. Thanks.
