### ISSUE TITLE
HTML5 content not working

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri-server#24]
Am unable to successfully load any of these or any HTML5 content from public CK-12 channel -
```CK-12 ->  Grade 1 -> Elementary Math -> Math```
Flexbooks load after a long delay with missing images.
PLIX content stops at 90%.

![ck12-plix](https://user-images.githubusercontent.com/2577060/63019119-1f4e5d00-beb8-11e9-8577-ee89ddd10ca2.png)

Channel token - ```lirub-laruk``` - any HTML5 content there.

![cspathshala](https://user-images.githubusercontent.com/2577060/63019148-2d03e280-beb8-11e9-8fe7-28e45f2e9e2a.png)

This seems a kolibri-server specific issue because the same content loads and is accessible in when tested in these environments -
kolibri deb on Ubuntu 18.04 
kolibri on Windows

Tried deleting the channels and reimporting the content. The end result is the same.

*Environment:*
Ubuntu 18.04
kolibri-server 0.3.0 
kolibri 0.12.7

**Comment by radinamatic** [comment]
Possibly related to https://github.com/learningequality/kolibri/issues/5851.

**Comment by radinamatic** [comment]
Oops, didn't see that it was already mentioned... 🤦‍♀

**Comment by jredrejo** [comment]
Confirmed the problem happens with kolibri-server and not kolibri, both with kolibri 0.12.7 & 0.12.8
