### ISSUE TITLE
debconf warning during kolibri-server start 

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri-server#25]
```systemctl start kolibri-server``` always shows this warning - 
```Aug 14 17:30:12 server kolibri-server[7303]: debconf: DbDriver "passwords" warning: could not open /var/cache/debconf/passwords.dat: Permission denied```

*Environment:*
Ubuntu 18.04
kolibri-server 0.3.0
kolibri 0.12.7

**Comment by jredrejo** [comment]
Sorry but that's an ubuntu bug that has been reported in several issues in Ubuntu. kolibri-server can't do anything to avoid it
