### ISSUE TITLE
Running kolibri.service is required

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-server#27]
When installing Kolibri, it's actually optional to run the service. Installing `kolibri-server` will then disable Cherry Py for the `kolibri.service` instance, hence it will only be responsible for background tasks.

In kolibri-server 0.3.1, `Requires: kolibri.service` was removed from `kolibri-server.service`. Is this a problem? Should we add `systemctl enable kolibri.service` to `postinst` for `kolibri-server` or similar?

![image](https://user-images.githubusercontent.com/374612/63370463-8a010c00-c382-11e9-930d-a3b38f3c73ac.png)

**Comment by jredrejo** [comment]
@benjaoming  It was removed because it's started by the `kolibri-server`init. Doing it as you proposed would make `kolibri`start twice

**Comment by benjaoming** [comment]
@jredrejo 

NOW I GET IT! :)

Yes, I just saw that the `.service` file had the dependency removed, but now I see that `.init`starts it: https://github.com/learningequality/kolibri-server/blob/8155e93579b1440f621006dd74ac5b50cd4d4fd2/debian/kolibri-server.init#L57

Thanks!
