### ISSUE TITLE
select error page language based on client header

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-server#37]
When the user navigates to a URL without a language code (e.g. localhost:8080), we should preferably set the language based on the `Accept-Language` header.

Follow-up from https://github.com/learningequality/kolibri-server/pull/35

**Comment by jredrejo** [comment]
It's a real pitty Debian does not include the optional [nginx Accept Language module](https://www.nginx.com/resources/wiki/modules/accept_language/) in the  [nginx-extras package](https://packages.debian.org/buster/nginx-extras ) . It would make this config very simple and easy to implement.
I see there have been a [bug open](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=897425) for more than one year, so it seems they are not in a hurry to add it.

Depending on how important this is considered we could keep waiting or look for some other possible alternatives, as the ones explained at https://stackoverflow.com/questions/3657614/how-to-rewrite-location-in-nginx-depending-on-the-client-browsers-language (None of them seem to have the complete approval but we could test them in our system configuration)

**Comment by indirectlylit** [comment]
I think this is "nice to have" but probably not super important at the moment. An easier and more important change might be to simply allow language switching, e.g.: https://github.com/learningequality/kolibri-server/issues/38

However, I don't think even that is critical for 0.13.0. The existing change is already a huge improvement, so let's return to this for the next major release.

**Comment by jredrejo** [comment]
Closing as `won't fix`. In case this is still a required feature, it should be requested on `kolibri` repository as this package relies on kolibri `loadingpage` command to generate the help pages.
