### ISSUE TITLE
Allow language to be switched in error page

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-server#38]
Our selection of language is mostly a guess as to the actual intent of the user. Even if e.g. #37 were implemented, it might still be not the best language for the user in that moment.

In Kolibri, we allow users to switch their language within the app:

![image](https://user-images.githubusercontent.com/2367265/67502739-41dcbf00-f63b-11e9-9de5-7def277f1ca3.png)

We should provide similar functionality for the `kolibri-server` error pages.

**Comment by benjaoming** [comment]
What if the error page just contained all languages in one page? Switching could toggling the visibility of various error message translations as CSS elements. Toggling would be done w/ JS which could possibly be fine: https://stackoverflow.com/a/25603630

**Comment by jredrejo** [comment]
> What if the error page just contained all languages in one page?

Honestly, I don't know what to think: in one comment you asked to remove JavaScript and in this you suggest to add more JavaScript.
For all this work I would like to keep focus on the fact that it's just an error page. I don't think too many resources should be invested in this work and we should try to keep it simple. It's not a new application, in fact, the final goal should be avoid this page is ever shown ;)

**Comment by benjaoming** [comment]
> Honestly, I don't know what to think: in one comment you asked to remove JavaScript and in this you suggest to add more JavaScript.

It's not a position that I uphold in a very dogmatic way, I took for granted that we are now using JS for the benefits it can bring about. One of them would be to steer around the issue that was mentioned in #37.

**Comment by indirectlylit** [comment]
Yes, agreed that putting all user-facing text in a single HTML page and switching language with JS would be a clever way to avoid writing complicated nginx language-switching logic; however it would certainly add complexity to the current crowdin workflow.

**Comment by jredrejo** [comment]
Closing as _won't fix_. In case this is still a required feature, it should be requested on kolibri repository as this package relies on kolibri `loadingpage` command to generate the help pages.
