### ISSUE TITLE
improve a11y of loading SVG

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-server#42]
We currently have a title that says "Kolibri Loader"

https://github.com/learningequality/kolibri-server/blob/0b311c5c77b540c49d0d6e69d29d6823161d0971/nginx_error_page/error.html#L108-L109

Something that would be more useful to somewhat using a screen reader would be "Kolibri is loading. Please wait"

We should also include an `aria-labelledby` attribute that points to the `<title>` tag in the `<svg>` tag. For more info, see http://web-accessibility.carnegiemuseums.org/code/svg/

**Comment by jredrejo** [comment]
Explanation to reopen it in the last comment of #72

**Comment by indirectlylit** [comment]
note - loader is purely decorative and doesn't need a `title` at all. Sorry for the confusion

**Comment by jredrejo** [comment]
After https://github.com/learningequality/kolibri/pull/10162 was merged, this is a responsability of kolibri, not kolibri-server. 
Text "kolibri is starting" was added there, fixing this issue.
