### ISSUE TITLE
Stopping kolibri-service leaves nginx running

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-server#44]
reported by @jamalex 

> Stopping kolibri-service leaves nginx running, with the kolibri-server virtualhost, showing loading page
> 
> **Observed:** Running `sudo service kolibri-server stop` seems to kill uwsgi, but leaves the nginx service running, so the port is still occupied and shows "Starting Kolibri" when you access it.
> 
> **Expected:** Port would no longer be occupied, and you wouldn't see the loading page. Perhaps can't shut down nginx entirely, but perhaps best to remove the conf from sites-enabled and reload nginx.

**Comment by jredrejo** [comment]
@jamalex I disagree with the expected behaviour. Nginx in a server can be used to serve other pages and applications. Stopping it when stopping kolibri-server could cause a catastrophe.
The current behaviour is on purpose.

**Comment by indirectlylit** [comment]
@jredrejo thoughts on Jamie's proposal? "remove the conf from sites-enabled and reload nginx"

**Comment by benjaoming** [comment]
I think that sounds like a hack.

If the Kolibri port should be freed, then `kolibri-server` must be uninstalled or one can manually remove the configuration from `sites-enabled` (that's a single step as well)

The use case for having `kolibri-server` installed and having its port used by some other service sounds a bit narrow.

As long as Nginx displays a placeholder when the UWSGI gateway is down, I think we have done our work and not left the user in state where it's not possible to understand what's going on.

Addressing this issue could be done through adding better / more information on said placeholder error page.

**Comment by jredrejo** [comment]
> @jredrejo thoughts on Jamie's proposal? "remove the conf from sites-enabled and reload nginx"

@indirectlylit 
As @benjaoming says, it sounds quite hacky and not too elegant. I understand the problem @jamalex faced. It's a quite common problem if you are installing/uninstalling/playing with the kolibri installation often. I have suffered it myself several times. However I think this is a special case and normal users should not have it: If you want kolibri-server you install it, if you don't , you uninstall it and everything returns to its original state, without stopping nginx at any moment.

Anyway, if there is a consensus about this, I won't oppose to implement the hack, it's quite trivial, we don't even  need to remove the configuration files, just enabling/disabling the `listen xxxx;` line in the nginx configuration should do it.

**Comment by benjaoming** [comment]
> Anyway, if there is a consensus about this, I won't oppose to implement the hack, it's quite trivial, we don't even need to remove the configuration files, just enabling/disabling the listen xxxx; line in the nginx configuration should do it.

I can be the one opposing to it then :) I kind of see any line of code with the risk of errors / maintenance etc.. so if there's no compelling reason to have it, there might be a compelling reason to _not_ have it :)

In this case, the hack has these issues:

1. That the error page is intended to be shown, even when the kolibri-server service is off?
1. That we get in to some unexpected enable/disable race condition

Suggesting that the this error perhaps targets a phrasing on the error page itself, moreover that Kolibri's "port occupied" error message perhaps is improved to suggest visiting the occupied service in a browser and see what it is :)

**Comment by indirectlylit** [comment]
All right - closing. Let's wait to see if user feedback comes in that people are confused by this behavior
