### ISSUE TITLE
Remove online fonts

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-server#47]
Following up on https://github.com/learningequality/kolibri-server/pull/46#discussion_r358894465

I don't think we should ever have online sources for the following reasons:

1. It implies: "For optimal experience, please ensure that all the clients have an internet connection".
1. Many deployments are behind captive portals, this will result in unnecessary requests and "301/200 OK" responses that don't contain valid font data.
1. The idea that fonts are cached doesn't really apply to clients that display the error page - clients running Kolibri have often never been online. Kolibri is made for the server to be sparsely online for sync'ing purposes.
1. People would expect Kolibri to be offline with all that this implies: Primarily that it's 100% offline, but secondarily that it isn't in touch with external servers for whatever privacy policies that may be at stake.
1. I think the right direction to go would be to enforce strict CSP headers such that we treat any request to an external source as an error in Kolibri.

I'd suggest to remove this entirely, so no one gets an impression that this page actually displays with a font. It'll have the same real-world effect, except that it won't imply the risk of slippery slopes or any other mis-conceptions about Kolibri's offline goals.

**Comment by jredrejo** [comment]
Honestly, I have nothing to argue in favour or against this request. These fonts improve the page, and the errors you mention are not visible at all unless you open the browser dev tools. I don't like seeing those errors but in this case they are benign. It's just a progressive app: it works well without Internet and it improves slightly the appearance if we don't have Internet.

My design-aesthetical skills are very limited and I am not able to decide if the tradeoffs are worth. 
In the worst case, if we consider we need the fonts and we also consider we can't make any Internet request under any circumstance,  we could check if including the fonts is legal and the work to do it is worth.
I leave this on your hands and @indirectlylit  or @khangmach  hands. The only point I have very clear is that this is not a priority thing, whatever decission is made.

**Comment by benjaoming** [comment]
> These fonts improve the page

Yes, haha, for that one, see my first point :)

**Comment by indirectlylit** [comment]
This is an example of [progressive enhancement](https://en.wikipedia.org/wiki/Progressive_enhancement). Users that have access to the internet will see the page in a style that matches our design system.

Users that do not have access to the internet will still have complete access to all the text. They will _not_ have any indication that their experience is different than other users. There are no "implications" - the behavior is completely hidden except to advanced users using developer tools.

> People would expect Kolibri to be offline with all that this implies: Primarily that it's 100% offline, but secondarily that it isn't in touch with external servers for whatever privacy policies that may be at stake.

People should not have this expectation. The application is not 100% offline, and reports stats back to our telemetry server as outlined in the privacy info page.
