### ISSUE TITLE
Relocate log file

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-server#49]
The uwsgi service currently writes to `~/.kolibri/uwsgi.log`, not in for instance `~/.kolibri/logs/uwsgi.log` (where all other Kolibri logs are found) nor `/var/log/uwsgi/app/` (the default location of UWSGI logs).

I am proposing to relocate the log to `~/.kolibri/logs/uwsgi.log` so it isn't missed, and making it easier for someone to zip their entire log directory for debugging elsewhere.

The default UWSGI log directory `/var/log/uwsgi/app/` is hardly useful for this, as I think most users won't know it beforehand, and there are likely no other UWSGI logs stored there, anyways.

CC: @jredrejo

**Comment by jredrejo** [comment]
It's a good idea, let's do it

**Comment by benjaoming** [comment]
Cool! It's a very simple change, I can do it if you like, I thought a bit about what to do with the old log file:

In order to avoid any race conditions, I will rename the old log file from `.kolibri/uwsgi.log` to `.kolibri/archive/uwsgi_pre-kolibri-server-0.3.7.log` inside the `kolibri-server.init` script, as there is a guarantee that UWSGI isn't already running when invoking the script's `do_start` function.

**Comment by benjaoming** [comment]
On a small related note, it would be nice if this log was readable by everyone, it is currently only readable by root:

```
pi@raspberrypi:~ $ tail -f .kolibri/uwsgi.log 
tail: cannot open '.kolibri/uwsgi.log' for reading: Permission denied
tail: no files remaining
```
