### ISSUE TITLE
kolibri-server does not work when port 80 is selected on a clean server

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri-server#52]
I installed kolibri-server into a fresh instance of Ubuntu Server 18.04, and selected "80" as the port during the installation process. After installation, going to http://127.0.0.1 gives the following default nginx config page:

![image](https://user-images.githubusercontent.com/618416/73580652-256ed080-443b-11ea-8b1c-2ce1ed7b72f5.png)

In order to get it working, I had to manually run `sudo rm /etc/nginx/sites-enabled/default` and then restart nginx. This isn't documented, and we don't flag to the user anything that might help with this.

**Comment by benjaoming** [comment]
> This isn't documented

I think we should add it as a debconf prompt, following the selection of port 80.

(if `/etc/nginx/sites-enabled/default` exists and port 80 is chosen)

```
Remove configuration for default Nginx virtualhost, currently occupying port 80?

This deletes /etc/nginx/sites-enabled/default
```

**Comment by jamalex** [comment]
That sounds good. And default option being "yes" (deleting).

It separately might also be good to just check the selected port (whatever it is) and see whether it's currently occupied, and allow them to select another if it is.

**Comment by benjaoming** [comment]
@jamalex agree on the default "yes"

I sense some complexity if we choose to have a debconf loop like `while "port 80 is occupied" do prompt()`, and perhaps if a non-nginx configuration has stolen port 80, the user might have more complex issues than our .deb scripts should/could handle

**Comment by jredrejo** [comment]
I think the easiest approach might be, in case port 80 is selected, doing a  backup copy of the current `default` and replace it by a `kolibri` config. No need to detect if it's occupied

**Comment by benjaoming** [comment]
@jredrejo it's a symlink, so removing it should be fine. Replacing it, to me, sounds confusing.
