### ISSUE TITLE
Logrotate config for uwsgi.log

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-server#56]
Ubuntu has log rotation automatically configured for the default UWSGI log folders. However, as we are running Kolibri as a different user, we have to put the log elsewhere and it makes total sense to have it in the `.kolibri` folder.

However, `logrotate` is a part of core Ubuntu systems, so it would make sense to distribute a default configuration.

```
 apt-cache rdepends --installed logrotate
logrotate
Reverse Depends:
  ubuntu-standard
  postgresql-common
  ubuntu-standard
  rsyslog
  postgresql-common
  cron
```

Here is the configuration in `/etc/logrotate.d/uwsgi` which I think we can just copy, adapt and call `/etc/logrotate.d/kolibri`:

```
"/var/log/uwsgi/*.log" "/var/log/uwsgi/app/*.log" {
  copytruncate
  daily
  rotate 5
  compress
  delaycompress
  missingok
  notifempty
}
```

**Comment by benjaoming** [comment]
As maybe be evident from https://github.com/learningequality/kolibri/issues/6459, we might receive quite a lot of entries during import of channels.

**Comment by jredrejo** [comment]
> As maybe be evident from [learningequality/kolibri#6459](https://github.com/learningequality/kolibri/issues/6459), we might receive quite a lot of entries during import of channels.

Not any more, with the latest uwsgi configuration
