### ISSUE TITLE
Should stop and restart be non-blocking

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-server#58]
In https://github.com/learningequality/kolibri-server/pull/54, I removed a "&" to fork and not wait for the kolibri stop/restart commands in the system service.

That was just to be cautious before releasing too many potentially dangerous changes (concurrent access to database, booting Kolibri etc).

CC: @jredrejo

**Comment by jredrejo** [comment]
Thanks, yes, I remember our chat conversation for this. I also tested it with the latest kolibri package and things have improved in the restart, so you were totally right with this change.
