### ISSUE TITLE
Modular nginx configuration

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-server#60]
We can improve and adapt Nginx for the following:

* Making it easy for some to disable the distributed Nginx configuration *respecting upgrade paths*
* Making configuration more modular, so it's easy to use Nginx `include` directives for distributed configurations

Ref: https://github.com/iiab/iiab/issues/1646

## Suggestions:

* Move main configuration to `/etc/nginx/sites-available` and symlink in `/etc/nginx/sites-enabled` (this symlink can then be removed by the user)
* Move various nginx configuration parts to `/etc/kolibri/`, perhaps:
  * `/etc/kolibri/dist/nginx_locations.conf`
  * `/etc/kolibri/dist/nginx_error_pages.conf`
  * `/etc/kolibri/dist/nginx_logging.conf`

Then `/etc/nginx/sites-available/kolibri.conf` would be the glue between all the configuration fragments.

**Comment by jredrejo** [comment]
Closed by #87
