### ISSUE TITLE
Concurrently stop kolibri services and UWSGI

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-server#62]
In https://github.com/learningequality/kolibri-server/pull/54#discussion_r408253342, it was proposed to add a `&` to fork `kolibri stop` to the background and continuing to stop the UWSGI service.

This can be re-added in a robust way to guarantee that kolibri is stopped when the service exits, such that  `systemctl restart kolibri-server` does not produce "race conditions" and fail to start kolibri because it hasn't stopped yet.

**Comment by benjaoming** [comment]
If kolibri fails to start after stopping (i.e. a restart): Implications of `systemctl restart kolibri-server` failing are especially bad for upgrades, as that produces a failed state in dpkg.

If not all issues related to exclusive db access have been solved, we also risk adding more weight to the "malformed" db burden.

**Comment by jredrejo** [comment]
closed via #54
