### ISSUE TITLE
Theoretical limit to size of log rotation

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-server#74]
Follow-up to: https://github.com/learningequality/kolibri-server/pull/53

It's possible to add for instance `size 100m` to the log rotation configuration to cap log files at 100 MB.

* What's the maximum size of a useful log file? (files should be rotated so they aren't impossible to attach in emails, forum posts etc)
* What's the maximum combined size of all stored log files

https://stackoverflow.com/questions/20162176/centos-linux-setting-logrotate-to-maximum-file-size-for-all-logs

**Comment by jredrejo** [comment]
Closed by #87
