### ISSUE TITLE
Prepare kolibri server to work with the changes to support hashi in 0.15.x

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri-server#82]
After
https://github.com/learningequality/kolibri/pull/7254
has been merged, changes to the uwsgi and nginx configs must be done to support this new way to injecting html files into kolibri

**Comment by rtibbles** [comment]
The main things that need to be done are:
* proxying the alternate origin server, and ensuring that the correct port is set in the Kolibri options for the proxied port
* simplifying how we serve the zipcontent endpoint as we no longer need to patch the CSP header, as the origin is no longer null when accessed in the client side.

**Comment by jredrejo** [comment]
Closed by #87
