### ISSUE TITLE
kolibri-server.service times out for installations with large content repositories

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri-server#92]
Have encountered cases wherein content repository is quite large (greater than 100 GB, in my case), kolibri-server fails to start with a timeout error.
This happens during upgrade and for each subsequent start. I was upgrading from Kolibri 0.14.7.

Hardware: Celeron Dual Core N3050 + 4 GB RAM
Software:
kolibri-server package version 0.4.0-0ubuntu2
kolibri package version  0.15.0-0ubuntu1
Ubuntu 18.04.6

The solution that works for me is adding `TimeoutStartSec=infinity` to `/lib/systemd/system/kolibri-server.service`'s `[Service]` section.

**Comment by intelliant01** [comment]
Noticed that the service fails every time during upgrade but may start successfully in subsequent starts if once started with `TimeoutStartSec=infinity` to complete the upgrade routine.
However, a successful start without `TimeoutStartSec=infinity` is random but success with `TimeoutStartSec=infinity` is certain.

**Comment by jredrejo** [comment]
`TimeoutStartSec=infinity`
can not be generally applied as it cause issues when rebooting or stoping the server.
If migrations are causing a time out (what can be logical if it takes too long to be applied) we should find a better solution for this particular case.

**Comment by intelliant01** [comment]
The very same reason(s) that [`kolibri.service`](https://github.com/learningequality/kolibri-installer-debian/blob/efbf9d38cae77ba1ba8074cd63eb29ceb76e318b/debian/startup/kolibri.service#L13) has `TimeoutStartSec=infinity` should apply herein. Isn't it?

**Comment by intelliant01** [comment]
@jredrejo I see your reasoning in some detail at https://github.com/learningequality/kolibri-server/pull/54. What additional information do you need from me to further diagnose the delay and address this further?

**Comment by intelliant01** [comment]
And `kolibri-server` always fails to stop cleanly and the status always shows as `failed` whenever I have attempted to stop it. This is the state on more than 6 servers that I have upgraded over the last 2 weeks. All are of the same configuration as mentioned above.

```
root@server:~# systemctl stop kolibri-server
root@server:~# systemctl status kolibri-server kolibri
● kolibri-server.service - A high performance web server setup for Kolibri
   Loaded: loaded (/lib/systemd/system/kolibri-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2022-01-19 16:45:33 IST; 1s ago
  Process: 12784 ExecStop=/etc/init.d/kolibri-server stop (code=exited, status=1/FAILURE)
  Process: 12623 ExecStart=/etc/init.d/kolibri-server start (code=exited, status=0/SUCCESS)

Jan 19 16:45:15 server systemd[1]: Stopping A high performance web server setup for Kolibri...
Jan 19 16:45:16 server runuser[12799]: pam_unix(runuser:session): session opened for user mssadmin by (uid=0)
Jan 19 16:45:25 server kolibri-server[12784]: WARNING  Option CHERRYPY_START in section [Server] is deprecated, please remove it from your options.ini file
Jan 19 16:45:25 server kolibri-server[12784]: INFO     Option DEBUG in section [Server] being overridden by environment variable KOLIBRI_DEBUG
Jan 19 16:45:25 server kolibri-server[12784]: INFO     Option DEBUG_LOG_DATABASE in section [Server] being overridden by environment variable KOLIBRI_DEBUG_
Jan 19 16:45:30 server kolibri-server[12784]: INFO     Kolibri background services have successfully been stopped.
Jan 19 16:45:30 server runuser[12799]: pam_unix(runuser:session): session closed for user mssadmin
Jan 19 16:45:33 server systemd[1]: kolibri-server.service: Control process exited, code=exited status=1
Jan 19 16:45:33 server systemd[1]: kolibri-server.service: Failed with result 'exit-code'.
Jan 19 16:45:33 server systemd[1]: Stopped A high performance web server setup for Kolibri.

● kolibri.service - LSB: kolibri daemon, an offline education platform
   Loaded: loaded (/etc/init.d/kolibri; disabled; vendor preset: enabled)
   Active: inactive (dead)
```
Not sure if I should create a separate issue for this. Should I?

**Comment by intelliant01** [comment]
@jredrejo ~I have not been able to reproduce the issue with starting up post upgrades for the last few days.~ Just encountered the issue again. I shall be watching this for any upgrades for another few weeks.
The problem of a [clean shutdown](https://github.com/learningequality/kolibri-server/issues/92#issuecomment-1016722691) is definitely still there.

**Comment by intelliant01** [comment]
@jredrejo I have encountered the timeout issue on multiple installations. And each time adding `TimeoutStartSec=infinity` resolves the same.
The installation hardware is Celeron 3050 + 4 GB RAM on which kolibri-server fails to start because the system load is too high during startup.
