### ISSUE TITLE
Raspberry Pi image v0.17.0-beta3 - Cannot import channels when accessing Kolibri at the default http://10.10.10.10

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri-server#98]
## Observed behavior

When using the Raspberry Pi image v0.17.0-beta3 I can't import channels when accessing Kolibri at the default `http://10.10.10.10`. If I delete the .kolibri folder and restart the server then Kolibri is available at `http://10.10.10.10:8080` and everything is working normally.

Logs:

[RasPiLogs.zip](https://github.com/user-attachments/files/16267994/RasPiLogs.zip)

## Expected behavior

Kolibri should be working fine at the default `http://10.10.10.10` address
## Steps to reproduce the issue

1. Run the Raspberry Pi image from https://github.com/learningequality/kolibri/releases/tag/v0.17.0-beta3
2. Attempt to import channels from USB or devices in the network

## Usage Details
Raspberry Pi 4

**Comment by pcenov** [comment]
@radinamatic

**Comment by jredrejo** [comment]
As confirmed in conversations with @pcenov  it seems content can be accessed from uwgi, probably to some configuration changes in kolibri 0.17

Several
`WARNING  2024-07-16 03:20:52,011 Not Found: /device/api/device_channel/95a52b386f2c485cb97dd60901674a98/ `
messages can be seen in uwsgi.log

**Comment by radinamatic** [comment]
Re-tested with the RPi 4 image that included these, and the import is working again out of the box! 👏🏽 
 
https://github.com/learningequality/kolibri-server/commit/fdf8efa3c31d7df2ecc6f0da30a0e0f82cb9c361 
https://github.com/learningequality/kolibri-server/pull/99

**Comment by radinamatic** [comment]
Closing as fixed! 💥
